// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqY_IzdH3_8dWyLs4e3JzC_TXXaPULlTs',
    appId: '1:431464096968:android:12e7262e6db51ab22431fd',
    messagingSenderId: '431464096968',
    projectId: 'bookapp-22ae8',
    storageBucket: 'bookapp-22ae8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJfQ-_kLcKApG85W9BGD2xb6UZNA1XNo',
    appId: '1:431464096968:ios:8c929a2c9f3992f32431fd',
    messagingSenderId: '431464096968',
    projectId: 'bookapp-22ae8',
    storageBucket: 'bookapp-22ae8.firebasestorage.app',
    androidClientId:
        '431464096968-if6330amrljro5q8fhrsbd6q6puv1h4t.apps.googleusercontent.com',
    iosClientId:
        '431464096968-ajb012a1a772u295rbt06ns4t3ru4nh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJfQ-_kLcKApG85W9BGD2xb6UZNA1XNo',
    appId: '1:431464096968:ios:8c929a2c9f3992f32431fd',
    messagingSenderId: '431464096968',
    projectId: 'bookapp-22ae8',
    storageBucket: 'bookapp-22ae8.firebasestorage.app',
    androidClientId:
        '431464096968-if6330amrljro5q8fhrsbd6q6puv1h4t.apps.googleusercontent.com',
    iosClientId:
        '431464096968-ajb012a1a772u295rbt06ns4t3ru4nh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookapp',
  );
}
